# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/tiny-tokenizer',
                'doc_host': 'https://numb3r33.github.io',
                'git_url': 'https://github.com/numb3r33/tiny-tokenizer',
                'lib_path': 'tiny_tokenizer'},
  'syms': {'tiny_tokenizer.core': {'tiny_tokenizer.core.foo': ('core.html#foo', 'tiny_tokenizer/core.py')}}}
